// Lista de versículos do "Palavra para hoje". Para incluir mais, basta adicionar itens.
// O versículo do dia é escolhido automaticamente pela data, sem manutenção.
window.VERSICULOS = [
    { ref: 'João 3:16', texto: 'Porque Deus amou ao mundo de tal maneira que deu o seu Filho unigênito, para que todo o que nele crê não pereça, mas tenha a vida eterna.' },
    { ref: 'Salmos 23:1', texto: 'O Senhor é o meu pastor; nada me faltará.' },
    { ref: 'Filipenses 4:13', texto: 'Tudo posso naquele que me fortalece.' },
    { ref: 'Provérbios 3:5-6', texto: 'Confia no Senhor de todo o teu coração e não te estribes no teu próprio entendimento. Reconhece-o em todos os teus caminhos, e ele endireitará as tuas veredas.' },
    { ref: 'Isaías 41:10', texto: 'Não temas, porque eu sou contigo; não te assombres, porque eu sou o teu Deus; eu te fortaleço, e te ajudo, e te sustento com a destra da minha justiça.' },
    { ref: 'Josué 1:9', texto: 'Não to mandei eu? Sê forte e corajoso; não temas, nem te espantes, porque o Senhor, teu Deus, é contigo, por onde quer que andares.' },
    { ref: 'Romanos 8:28', texto: 'Sabemos que todas as coisas cooperam para o bem daqueles que amam a Deus, daqueles que são chamados segundo o seu propósito.' },
    { ref: 'Mateus 11:28', texto: 'Vinde a mim, todos os que estais cansados e sobrecarregados, e eu vos aliviarei.' },
    { ref: 'Salmos 46:1', texto: 'Deus é o nosso refúgio e fortaleza, socorro bem presente nas tribulações.' },
    { ref: 'Jeremias 29:11', texto: 'Porque eu bem sei os pensamentos que tenho a vosso respeito, diz o Senhor; pensamentos de paz e não de mal, para vos dar o fim que esperais.' },
    { ref: 'Mateus 6:33', texto: 'Buscai, pois, em primeiro lugar, o seu reino e a sua justiça, e todas estas coisas vos serão acrescentadas.' },
    { ref: 'Salmos 121:1-2', texto: 'Elevo os olhos para os montes: de onde me virá o socorro? O meu socorro vem do Senhor, que fez os céus e a terra.' },
    { ref: '1 Coríntios 13:13', texto: 'Agora, pois, permanecem a fé, a esperança e o amor, estes três; porém o maior destes é o amor.' },
    { ref: 'Hebreus 11:1', texto: 'Ora, a fé é a certeza de coisas que se esperam, a convicção de fatos que se não veem.' },
    { ref: 'Salmos 27:1', texto: 'O Senhor é a minha luz e a minha salvação; de quem terei temor? O Senhor é a fortaleza da minha vida; de quem me recearei?' },
    { ref: 'Mateus 5:16', texto: 'Assim brilhe também a vossa luz diante dos homens, para que vejam as vossas boas obras e glorifiquem a vosso Pai, que está nos céus.' },
    { ref: 'João 14:6', texto: 'Disse-lhe Jesus: Eu sou o caminho, e a verdade, e a vida; ninguém vem ao Pai senão por mim.' },
    { ref: 'João 14:27', texto: 'Deixo-vos a paz, a minha paz vos dou; não vo-la dou como o mundo a dá. Não se turbe o vosso coração, nem se atemorize.' },
    { ref: 'Filipenses 4:6', texto: 'Não andeis ansiosos de coisa alguma; em tudo, porém, sejam conhecidas diante de Deus as vossas petições, pela oração e pela súplica, com ações de graças.' },
    { ref: '1 Pedro 5:7', texto: 'Lançando sobre ele toda a vossa ansiedade, porque ele tem cuidado de vós.' },
    { ref: 'Salmos 37:4', texto: 'Agrada-te do Senhor, e ele satisfará os desejos do teu coração.' },
    { ref: 'Isaías 40:31', texto: 'Mas os que esperam no Senhor renovam as suas forças, sobem com asas como águias; correm e não se cansam; caminham e não se fatigam.' },
    { ref: 'Romanos 8:31', texto: 'Que diremos, pois, à vista destas coisas? Se Deus é por nós, quem será contra nós?' },
    { ref: 'Lamentações 3:22-23', texto: 'As misericórdias do Senhor são a causa de não sermos consumidos, porque as suas misericórdias não têm fim; renovam-se cada manhã. Grande é a tua fidelidade.' },
    { ref: 'Salmos 118:24', texto: 'Este é o dia que o Senhor fez; regozijemo-nos e alegremo-nos nele.' },
    { ref: 'Efésios 2:8', texto: 'Porque pela graça sois salvos, mediante a fé; e isto não vem de vós; é dom de Deus.' },
    { ref: '2 Coríntios 5:17', texto: 'E assim, se alguém está em Cristo, é nova criatura; as coisas antigas já passaram; eis que se fizeram novas.' },
    { ref: 'Provérbios 18:10', texto: 'Torre forte é o nome do Senhor, à qual o justo se acolhe e está seguro.' },
    { ref: 'Mateus 28:20', texto: 'E eis que estou convosco todos os dias até à consumação do século.' },
    { ref: 'Salmos 34:8', texto: 'Provai e vede que o Senhor é bom; bem-aventurado o homem que nele se refugia.' },
    { ref: 'Tiago 1:5', texto: 'Se, porém, algum de vós necessita de sabedoria, peça-a a Deus, que a todos concede liberalmente e nada lhes impropera, e ser-lhe-á concedida.' },
    { ref: '1 João 4:19', texto: 'Nós amamos porque ele nos amou primeiro.' },
    { ref: 'Colossenses 3:23', texto: 'E tudo o que fizerdes, fazei-o de todo o coração, como ao Senhor e não aos homens.' },
    { ref: 'Salmos 119:105', texto: 'Lâmpada para os meus pés é a tua palavra e luz para o meu caminho.' },
    { ref: 'Provérbios 16:3', texto: 'Confia ao Senhor as tuas obras, e teus desígnios serão estabelecidos.' },
    { ref: 'Romanos 15:13', texto: 'O Deus da esperança vos encha de todo o gozo e paz no vosso crer, para que sejais ricos de esperança no poder do Espírito Santo.' },
    { ref: 'Hebreus 13:8', texto: 'Jesus Cristo é o mesmo, ontem, e hoje, e eternamente.' },
    { ref: 'João 8:12', texto: 'Eu sou a luz do mundo; quem me segue não andará em trevas, mas terá a luz da vida.' },
    { ref: 'Miqueias 6:8', texto: 'Ele te declarou, ó homem, o que é bom e que é o que o Senhor pede de ti: que pratiques a justiça, e ames a misericórdia, e andes humildemente com o teu Deus.' },
    { ref: '1 Tessalonicenses 5:16-18', texto: 'Alegrai-vos sempre. Orai sem cessar. Em tudo dai graças, porque esta é a vontade de Deus em Cristo Jesus para convosco.' }
];
